In [1]:
import numpy as np
import pandas as pd

In [2]:
movies=pd.read_csv('tmdb_5000_movies.csv')
credits=pd.read_csv('tmdb_5000_credits.csv')

In [3]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [4]:
movies.iloc[1]['genres']

'[{"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 28, "name": "Action"}]'

In [5]:
movies.iloc[1]['keywords']

'[{"id": 270, "name": "ocean"}, {"id": 726, "name": "drug abuse"}, {"id": 911, "name": "exotic island"}, {"id": 1319, "name": "east india trading company"}, {"id": 2038, "name": "love of one\'s life"}, {"id": 2052, "name": "traitor"}, {"id": 2580, "name": "shipwreck"}, {"id": 2660, "name": "strong woman"}, {"id": 3799, "name": "ship"}, {"id": 5740, "name": "alliance"}, {"id": 5941, "name": "calypso"}, {"id": 6155, "name": "afterlife"}, {"id": 6211, "name": "fighter"}, {"id": 12988, "name": "pirate"}, {"id": 157186, "name": "swashbuckler"}, {"id": 179430, "name": "aftercreditsstinger"}]'

In [6]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [7]:
df = movies.merge(credits,on=['title'])

In [8]:
df=df[['movie_id','title','overview','genres','keywords','cast','crew']]

In [9]:
df.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4809 non-null   int64
 1   title     4809 non-null   object
 2   overview  4806 non-null   object
 3   genres    4809 non-null   object
 4   keywords  4809 non-null   object
 5   cast      4809 non-null   object
 6   crew      4809 non-null   object
dtypes: int64(1), object(6)
memory usage: 263.1+ KB

In [11]:
df = df.dropna()

In [12]:
df.duplicated().sum()

0

In [13]:
df.iloc[1]['genres']

'[{"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 28, "name": "Action"}]'

In [14]:
import ast

In [15]:
def extract_genres(txt):
    temp=[]
    txt = ast.literal_eval(txt)
    for i in txt:
        temp.append(i['name'])
        
    return temp

In [16]:
df['genres'] = df['genres'].apply(extract_genres)

In [17]:
df.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [18]:
df.iloc[1]['keywords']

'[{"id": 270, "name": "ocean"}, {"id": 726, "name": "drug abuse"}, {"id": 911, "name": "exotic island"}, {"id": 1319, "name": "east india trading company"}, {"id": 2038, "name": "love of one\'s life"}, {"id": 2052, "name": "traitor"}, {"id": 2580, "name": "shipwreck"}, {"id": 2660, "name": "strong woman"}, {"id": 3799, "name": "ship"}, {"id": 5740, "name": "alliance"}, {"id": 5941, "name": "calypso"}, {"id": 6155, "name": "afterlife"}, {"id": 6211, "name": "fighter"}, {"id": 12988, "name": "pirate"}, {"id": 157186, "name": "swashbuckler"}, {"id": 179430, "name": "aftercreditsstinger"}]'

In [19]:
def extract_keywords(txt):
    temp=[]
    txt = ast.literal_eval(txt)
    for i in txt:
        temp.append(i['name'])
        
    return temp

In [20]:
df['keywords'] = df['keywords'].apply(extract_genres)

In [21]:
df.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [22]:
df.iloc[1]['cast']

'[{"cast_id": 4, "character": "Captain Jack Sparrow", "credit_id": "52fe4232c3a36847f800b50d", "gender": 2, "id": 85, "name": "Johnny Depp", "order": 0}, {"cast_id": 5, "character": "Will Turner", "credit_id": "52fe4232c3a36847f800b511", "gender": 2, "id": 114, "name": "Orlando Bloom", "order": 1}, {"cast_id": 6, "character": "Elizabeth Swann", "credit_id": "52fe4232c3a36847f800b515", "gender": 1, "id": 116, "name": "Keira Knightley", "order": 2}, {"cast_id": 12, "character": "William \\"Bootstrap Bill\\" Turner", "credit_id": "52fe4232c3a36847f800b52d", "gender": 2, "id": 1640, "name": "Stellan Skarsg\\u00e5rd", "order": 3}, {"cast_id": 10, "character": "Captain Sao Feng", "credit_id": "52fe4232c3a36847f800b525", "gender": 2, "id": 1619, "name": "Chow Yun-fat", "order": 4}, {"cast_id": 9, "character": "Captain Davy Jones", "credit_id": "52fe4232c3a36847f800b521", "gender": 2, "id": 2440, "name": "Bill Nighy", "order": 5}, {"cast_id": 7, "character": "Captain Hector Barbossa", "credit_id": "52fe4232c3a36847f800b519", "gender": 2, "id": 118, "name": "Geoffrey Rush", "order": 6}, {"cast_id": 14, "character": "Admiral James Norrington", "credit_id": "52fe4232c3a36847f800b535", "gender": 2, "id": 1709, "name": "Jack Davenport", "order": 7}, {"cast_id": 13, "character": "Joshamee Gibbs", "credit_id": "52fe4232c3a36847f800b531", "gender": 2, "id": 2449, "name": "Kevin McNally", "order": 8}, {"cast_id": 11, "character": "Lord Cutler Beckett", "credit_id": "52fe4232c3a36847f800b529", "gender": 2, "id": 2441, "name": "Tom Hollander", "order": 9}, {"cast_id": 19, "character": "Tia Dalma", "credit_id": "52fe4232c3a36847f800b549", "gender": 1, "id": 2038, "name": "Naomie Harris", "order": 10}, {"cast_id": 8, "character": "Governor Weatherby Swann", "credit_id": "52fe4232c3a36847f800b51d", "gender": 2, "id": 378, "name": "Jonathan Pryce", "order": 11}, {"cast_id": 37, "character": "Captain Teague Sparrow", "credit_id": "52fe4232c3a36847f800b5b3", "gender": 2, "id": 1430, "name": "Keith Richards", "order": 12}, {"cast_id": 16, "character": "Pintel", "credit_id": "52fe4232c3a36847f800b53d", "gender": 2, "id": 1710, "name": "Lee Arenberg", "order": 13}, {"cast_id": 15, "character": "Ragetti", "credit_id": "52fe4232c3a36847f800b539", "gender": 2, "id": 1711, "name": "Mackenzie Crook", "order": 14}, {"cast_id": 18, "character": "Lieutenant Theodore Groves", "credit_id": "52fe4232c3a36847f800b545", "gender": 2, "id": 4031, "name": "Greg Ellis", "order": 15}, {"cast_id": 55, "character": "Cotton", "credit_id": "57e28d2ec3a3681a01005b5c", "gender": 2, "id": 1715, "name": "David Bailie", "order": 16}, {"cast_id": 17, "character": "Marty", "credit_id": "52fe4232c3a36847f800b541", "gender": 2, "id": 4030, "name": "Martin Klebba", "order": 17}, {"cast_id": 57, "character": "Ian Mercer", "credit_id": "57e28d78c3a36808b900bf4f", "gender": 0, "id": 939, "name": "David Schofield", "order": 18}, {"cast_id": 62, "character": "Scarlett", "credit_id": "57e28ec5c3a3681a50005855", "gender": 1, "id": 2450, "name": "Lauren Maher", "order": 19}, {"cast_id": 63, "character": "Giselle", "credit_id": "57e28ed692514123f5005635", "gender": 1, "id": 2452, "name": "Vanessa Branch", "order": 20}, {"cast_id": 60, "character": "Mullroy", "credit_id": "57e28db2c3a3681a01005bc7", "gender": 2, "id": 1714, "name": "Angus Barnett", "order": 21}, {"cast_id": 59, "character": "Murtogg", "credit_id": "57e28da192514118f7006008", "gender": 0, "id": 1713, "name": "Giles New", "order": 22}, {"cast_id": 58, "character": "Tai Huang", "credit_id": "57e28d8ec3a3681a01005bab", "gender": 2, "id": 22075, "name": "Reggie Lee", "order": 23}, {"cast_id": 64, "character": "Henry Turner", "credit_id": "57e29119925141151100a6cc", "gender": 2, "id": 61259, "name": "Dominic Scott Kay", "order": 24}, {"cast_id": 39, "character": "Mistress Ching", "credit_id": "52fe4232c3a36847f800b5bd", "gender": 1, "id": 33500, "name": "Takayo Fischer", "order": 25}, {"cast_id": 40, "character": "Lieutenant Greitzer", "credit_id": "52fe4232c3a36847f800b5c1", "gender": 2, "id": 1224149, "name": "David Meunier", "order": 26}, {"cast_id": 49, "character": "Hadras", "credit_id": "56d1871c92514174680010cf", "gender": 2, "id": 429401, "name": "Ho-Kwan Tse", "order": 27}, {"cast_id": 56, "character": "Clacker", "credit_id": "57e28d4b92514125710055cb", "gender": 0, "id": 1123, "name": "Andy Beckwith", "order": 28}, {"cast_id": 51, "character": "Penrod", "credit_id": "56ec8c14c3a3682260003c53", "gender": 2, "id": 1056117, "name": "Peter Donald Badalamenti II", "order": 29}, {"cast_id": 61, "character": "Cotton\'s Parrot (voice)", "credit_id": "57e28dcc9251412463005678", "gender": 2, "id": 21700, "name": "Christopher S. Capp", "order": 30}, {"cast_id": 65, "character": "Captain Teague", "credit_id": "58bc2a37c3a368663003740b", "gender": 2, "id": 1430, "name": "Keith Richards", "order": 31}, {"cast_id": 66, "character": "Captain Jocard", "credit_id": "58bc2a8e925141609e03a179", "gender": 2, "id": 2603, "name": "Hakeem Kae-Kazim", "order": 32}, {"cast_id": 67, "character": "Captain Ammand", "credit_id": "58e2a21ac3a36872af00f9c2", "gender": 0, "id": 70577, "name": "Ghassan Massoud", "order": 33}]'

In [23]:
def extract_cast(txt):
    temp=[]
    counter=0
    txt = ast.literal_eval(txt)
    for i in txt:
        if(counter!=3):
            temp.append(i['name'])
            counter=counter+1
        else:
            break
    return temp

In [24]:
df['cast'] = df['cast'].apply(extract_cast)

In [25]:
df.iloc[1]['crew']

'[{"credit_id": "52fe4232c3a36847f800b579", "department": "Camera", "gender": 2, "id": 120, "job": "Director of Photography", "name": "Dariusz Wolski"}, {"credit_id": "52fe4232c3a36847f800b4fd", "department": "Directing", "gender": 2, "id": 1704, "job": "Director", "name": "Gore Verbinski"}, {"credit_id": "52fe4232c3a36847f800b54f", "department": "Production", "gender": 2, "id": 770, "job": "Producer", "name": "Jerry Bruckheimer"}, {"credit_id": "52fe4232c3a36847f800b503", "department": "Writing", "gender": 2, "id": 1705, "job": "Screenplay", "name": "Ted Elliott"}, {"credit_id": "52fe4232c3a36847f800b509", "department": "Writing", "gender": 2, "id": 1706, "job": "Screenplay", "name": "Terry Rossio"}, {"credit_id": "52fe4232c3a36847f800b57f", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "52fe4232c3a36847f800b585", "department": "Editing", "gender": 2, "id": 1722, "job": "Editor", "name": "Craig Wood"}, {"credit_id": "52fe4232c3a36847f800b573", "department": "Sound", "gender": 2, "id": 947, "job": "Original Music Composer", "name": "Hans Zimmer"}, {"credit_id": "52fe4232c3a36847f800b555", "department": "Production", "gender": 2, "id": 2444, "job": "Executive Producer", "name": "Mike Stenson"}, {"credit_id": "52fe4232c3a36847f800b561", "department": "Production", "gender": 2, "id": 2445, "job": "Producer", "name": "Eric McLeod"}, {"credit_id": "52fe4232c3a36847f800b55b", "department": "Production", "gender": 2, "id": 2446, "job": "Producer", "name": "Chad Oman"}, {"credit_id": "52fe4232c3a36847f800b567", "department": "Production", "gender": 0, "id": 2447, "job": "Producer", "name": "Peter Kohn"}, {"credit_id": "52fe4232c3a36847f800b56d", "department": "Production", "gender": 0, "id": 2448, "job": "Producer", "name": "Pat Sandston"}, {"credit_id": "52fe4232c3a36847f800b58b", "department": "Production", "gender": 1, "id": 2215, "job": "Casting", "name": "Denise Chamian"}, {"credit_id": "52fe4232c3a36847f800b597", "department": "Art", "gender": 2, "id": 1226, "job": "Production Design", "name": "Rick Heinrichs"}, {"credit_id": "52fe4232c3a36847f800b59d", "department": "Art", "gender": 2, "id": 553, "job": "Art Direction", "name": "John Dexter"}, {"credit_id": "52fe4232c3a36847f800b591", "department": "Production", "gender": 1, "id": 3311, "job": "Casting", "name": "Priscilla John"}, {"credit_id": "52fe4232c3a36847f800b5a3", "department": "Art", "gender": 1, "id": 4032, "job": "Set Decoration", "name": "Cheryl Carasik"}, {"credit_id": "52fe4232c3a36847f800b5a9", "department": "Costume & Make-Up", "gender": 0, "id": 4033, "job": "Costume Design", "name": "Liz Dann"}, {"credit_id": "52fe4232c3a36847f800b5af", "department": "Costume & Make-Up", "gender": 1, "id": 4034, "job": "Costume Design", "name": "Penny Rose"}, {"credit_id": "56427ce8c3a3686a53000d8b", "department": "Sound", "gender": 2, "id": 5132, "job": "Music Supervisor", "name": "Bob Badami"}, {"credit_id": "55993c15c3a36855db002f33", "department": "Art", "gender": 2, "id": 146439, "job": "Conceptual Design", "name": "James Ward Byrkit"}, {"credit_id": "52fe4232c3a36847f800b5b9", "department": "Costume & Make-Up", "gender": 1, "id": 406204, "job": "Makeup Department Head", "name": "Ve Neill"}, {"credit_id": "56e47f7892514132690017bd", "department": "Crew", "gender": 2, "id": 1259516, "job": "Stunts", "name": "John Dixon"}, {"credit_id": "5740be639251416597000849", "department": "Crew", "gender": 0, "id": 1336716, "job": "CGI Supervisor", "name": "Dottie Starling"}, {"credit_id": "56427c639251412fc8000dc1", "department": "Directing", "gender": 1, "id": 1344278, "job": "Script Supervisor", "name": "Pamela Alch"}, {"credit_id": "57083101c3a3681d320004e6", "department": "Crew", "gender": 0, "id": 1368867, "job": "Special Effects Coordinator", "name": "Allen Hall"}, {"credit_id": "56427d5ec3a3686a62000d4a", "department": "Sound", "gender": 0, "id": 1368884, "job": "Music Editor", "name": "Melissa Muik"}, {"credit_id": "56427c7b9251412fd4000e07", "department": "Directing", "gender": 1, "id": 1395290, "job": "Script Supervisor", "name": "Sharron Reynolds"}, {"credit_id": "56427d2bc3a3686a53000d9b", "department": "Sound", "gender": 0, "id": 1399327, "job": "Music Editor", "name": "Barbara McDermott"}, {"credit_id": "56427cb4c3a3686a53000d87", "department": "Directing", "gender": 1, "id": 1400738, "job": "Script Supervisor", "name": "Karen Golden"}, {"credit_id": "56427d169251412fd4000e23", "department": "Sound", "gender": 0, "id": 1534197, "job": "Music Editor", "name": "Katie Greathouse"}]'

In [26]:
def extract_director(txt):
    temp=[]
    txt = ast.literal_eval(txt)
    for i in txt:
        if(i['job']=='Director'):
            temp.append(i['name'])
            break
        
    return temp

In [27]:
df['crew'] = df['crew'].apply(extract_director)

In [28]:
df.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [29]:
df['genres'] = df['genres'].apply(lambda x:[i.replace(" ","")for i in x])
df['keywords'] = df['keywords'].apply(lambda x:[i.replace(" ","")for i in x])
df['cast'] = df['cast'].apply(lambda x:[i.replace(" ","")for i in x])
df['crew'] = df['crew'].apply(lambda x:[i.replace(" ","")for i in x])

In [30]:
df.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]

In [31]:
df['overview'] = df['overview'].apply(lambda x:x.split())

In [32]:
df['tags']=df['overview']+df['genres']+df['keywords']+df['cast']+df['crew']

In [33]:
df.head(1)

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."

In [34]:
df['tags'] = df['tags'].apply(lambda x:" ".join(x))

In [35]:
df['tags'] = df['tags'].apply(lambda x:x.lower())

In [36]:
df = df.drop(columns=['overview','genres','keywords','cast','crew'])

In [37]:
df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [38]:
df.iloc[1]['tags']

"captain barbossa, long believed to be dead, has come back to life and is headed to the edge of the earth with will turner and elizabeth swann. but nothing is quite as it seems. adventure fantasy action ocean drugabuse exoticisland eastindiatradingcompany loveofone'slife traitor shipwreck strongwoman ship alliance calypso afterlife fighter pirate swashbuckler aftercreditsstinger johnnydepp orlandobloom keiraknightley goreverbinski"

In [39]:
# import string

In [40]:
# def remove_punctuation(txt):
#     temp=[]
#     for i in txt.split():
#         if i not in string.punctuation:
#             temp.append(i)
    
#     return " ".join(temp)

In [41]:
# df['tags'].apply(remove_punctuation)

In [42]:
import nltk
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [43]:
#stemming
def stemming(txt):
    temp=[]
    for i in txt.split():
        i = ps.stem(i)
        temp.append(i)
        
    return " ".join(temp)

In [44]:
df['tags'] = df['tags'].apply(stemming)

In [45]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')

In [46]:
vectors = cv.fit_transform(df['tags']).toarray()

In [47]:
list(cv.get_feature_names_out())

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '17th',
 '18',
 '18th',
 '18thcenturi',
 '19',
 '1910',
 '1920',
 '1930',
 '1940',
 '1944',
 '1950',
 '1950s',
 '1960',
 '1960s',
 '1970',
 '1970s',
 '1971',
 '1974',
 '1976',
 '1980',
 '1985',
 '1990',
 '1999',
 '19th',
 '19thcenturi',
 '20',
 '200',
 '2003',
 '2009',
 '20th',
 '21st',
 '23',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '70',
 '80',
 'aaron',
 'aaroneckhart',
 'abandon',
 'abduct',
 'abigailbreslin',
 'abil',
 'abl',
 'aboard',
 'abov',
 'abus',
 'academ',
 'academi',
 'accept',
 'access',
 'accid',
 'accident',
 'acclaim',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'ace',
 'achiev',
 'acquaint',
 'act',
 'action',
 'actionhero',
 'activ',
 'activist',
 'activities',
 'actor',
 'actress',
 'actual',
 'ad',
 'adam',
 'adamsandl',
 'adamshankman',
 'adapt',
 'add',
 'addict',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adopt',
 'ador',
 'adrienbrodi',
 'adult',
 'adultanim',
 'adulteri',
 'adulthood',
 'advanc',
 'adventur',
 'adventure',
 'adventures',
 'advertis',
 'advic',
 'advis',
 'affair',
 'affect',
 'afghanistan',
 'africa',
 'african',
 'africanamerican',
 'aftercreditssting',
 'afterlif',
 'aftermath',
 'ag',
 'age',
 'agediffer',
 'agenc',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggress',
 'ago',
 'agre',
 'ahead',
 'aid',
 'aidanquinn',
 'ail',
 'aim',
 'air',
 'airplan',
 'airplanecrash',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alaska',
 'albert',
 'alcatraz',
 'alcohol',
 'alecbaldwin',
 'alex',
 'alexkendrick',
 'alfredhitchcock',
 'alfredmolina',
 'ali',
 'alic',
 'alice',
 'alien',
 'alieninvas',
 'alienlife',
 'alienplanet',
 'aliens',
 'alik',
 'aliv',
 'alive',
 'allen',
 'alli',
 'allianc',
 'allow',
 'alon',
 'alongsid',
 'alpacino',
 'alpha',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'alyssa',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfri',
 'amateur',
 'amaz',
 'amazon',
 'ambassador',
 'ambit',
 'ambiti',
 'ambul',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americancivilwar',
 'americanfootbal',
 'americanfootballplay',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amus',
 'amusementpark',
 'amy',
 'amyadam',
 'amysmart',
 'ana',
 'anakin',
 'analyst',
 'anarchiccomedi',
 'ancient',
 'ancientrom',
 'ancientworld',
 'anderson',
 'andi',
 'andiemacdowel',
 'andrew',
 'android',
 'andy',
 'andygarcía',
 'angel',
 'angela',
 'angelabassett',
 'angeles',
 'angelinajoli',
 'anger',
 'angle',
 'angri',
 'ani',
 'anim',
 'animalattack',
 'animalhorror',
 'animals',
 'anjelicahuston',
 'ann',
 'anna',
 'annafari',
 'annakendrick',
 'anne',
 'annehathaway',
 'annemoss',
 'annetteben',
 'anni',
 'annie',
 'anniversari',
 'announc',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'ant',
 'antholog',
 'anthoni',
 'anthonyanderson',
 'anthonyhopkin',
 'anthropomorph',
 'anti',
 'antic',
 'antihero',
 'antiqu',
 'antoinefuqua',
 'antoniobandera',
 'antonyelchin',
 'anyon',
 'anyth',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apocalyps',
 'apocalypse',
 'apocalypt',
 'appar',
 'appear',
 'appl',
 'apple',
 'appoint',
 'appreci',
 'apprentic',
 'approach',
 'april',
 'aquarium',
 'arab',
 'arch',
 'archaeologist',
 'archeolog',
 'archer',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'aris',
 'aristocrat',
 'arm',
 'armi',
 'armor',
 'armsdeal',
 'army',
 'arnold',
 'arnoldschwarzenegg',
 'arrang',
 'arrangedmarriag',
 'arrest',
 'arriv',
 'arrog',
 'art',
 'arthur',
 'artifact',
 'artifici',
 'artificialintellig',
 'artist',
 'ash',
 'ashley',
 'ashleyjudd',
 'ashtonkutch',
 'asia',
 'asian',
 'asid',
 'ask',
 'aspect',
 'aspir',
 'assassin',
 'assault',
 'assembl',
 'assign',
 'assist',
 'assistant',
 'associ',
 'assum',
 'asteroid',
 'astronaut',
 'asylum',
 'atheist',
 'athlet',
 'atom',
 'atomicbomb',
 'attack',
 'attacks',
 'attempt',
 'attend',
 'attent',
 'attic',
 'attitud',
 'attorney',
 'attract',
 'auction',
 'audienc',
 'audit',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'autism',
 'auto',
 'automobilerac',
 'aveng',
 'averag',
 'avoid',
 'await',
 'awak',
 'awaken',
 'awar',
 'award',
 'away',
 'awkward',
 'awri',
 'awry',
 'ax',
 'babe',
 'babi',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backpack',
 'bad',
 'bag',
 'bahama',
 'bail',
 'balanc',
 'ball',
 'ballet',
 'balloon',
 'baltimor',
 'ban',
 'band',
 'bandit',
 'bangkok',
 'banish',
 'bank',
 'banker',
 'bankrobb',
 'bankrobberi',
 'bar',
 'barbrastreisand',
 'bare',
 'bargain',
 'barn',
 'barney',
 'baron',
 'barri',
 'barrylevinson',
 'barrysonnenfeld',
 'bas',
 'base',
 'basebal',
 'basedoncomicbook',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemus',
 'basedontrueev',
 'basedontruestori',
 'basedontvseri',
 'basedonvideogam',
 'basedonyoungadultnovel',
 'basement',
 'basketbal',
 'basketball',
 'bat',
 'batman',
 'battl',
 'battle',
 'battlefield',
 'bay',
 'beach',
 'beam',
 'bear',
 'beard',
 'beast',
 'beat',
 'beauti',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becam',
 'becaus',
 'becki',
 'becom',
 'becominganadult',
 'bed',
 'bedroom',
 'bee',
 'beer',
 'befor',
 'befriend',
 'began',
 'begin',
 'begins',
 'behavior',
 'belief',
 'believ',
 'bell',
 'bella',
 'belong',
 'belov',
 'ben',
 'benaffleck',
 'bend',
 'beneath',
 'benefit',
 'benfost',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstil',
 'bent',
 'berlin',
 'best',
 'bestfriend',
 'bestfriendsinlov',
 'bet',
 'beth',
 'betray',
 'bettemidl',
 'better',
 'betti',
 'beverli',
 'bibl',
 'bid',
 'big',
 'bigger',
 'biggest',
 'bike',
 'biker',
 'bikini',
 'billhad',
 'billi',
 'billionair',
 'billmurray',
 'billnighi',
 'billpaxton',
 'billpullman',
 'billybobthornton',
 'billycrudup',
 'billycryst',
 'biographi',
 'biolog',
 'bird',
 'birth',
 'birthday',
 'bisexu',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarr',
 'black',
 'blackmag',
 'blackmail',
 'blackpeopl',
 'blacksmith',
 'blade',
 'blame',
 'blend',
 'blind',
 'bliss',
 'blizzard',
 'block',
 'blond',
 'blood',
 'bloodi',
 'bloodsplatt',
 'bloodthirsti',
 'blow',
 'blue',
 'board',
 'boardingschool',
 'boat',
 'bob',
 'bobbi',
 'bobbyfarrelli',
 'bobhoskin',
 'bodi',
 'body',
 'bodyguard',
 'bold',
 'bollywood',
 'bomb',
 'bond',
 'bone',
 'book',
 'border',
 'bore',
 'boredom',
 'born',
 'boss',
 'boston',
 'botch',
 'bound',
 'boundari',
 'bounti',
 'bountyhunt',
 'bout',
 'box',
 'boxer',
 'boy',
 'boyfriend',
 'boys',
 'bradleycoop',
 'bradpitt',
 'brain',
 'brainwash',
 'brand',
 'brandon',
 'brave',
 'braveri',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breast',
 'breath',
 'breed',
 'brendanfras',
 'brendangleeson',
 'brent',
 'brettratn',
 'brian',
 'briandepalma',
 'bride',
 'bridesmaid',
 'bridg',
 'brief',
 'brielarson',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'britishsecretservic',
 'brittanymurphi',
 'broadcast',
 'broadway',
 'broke',
 'broken',
 'broker',
 'bronx',
 'brook',
 'brooklyn',
 'broom',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucegreenwood',
 'brucewilli',
 'brutal',
 'bryansing',
 'bu',
 'buck',
 'bud',
 'buddi',
 'buddy',
 'buddycomedi',
 'buddycop',
 'budget',
 'build',
 'building',
 'built',
 'bullet',
 'bulli',
 'bumbl',
 'bunch',
 'bunker',
 'bunni',
 'burglar',
 'buri',
 'burn',
 'bush',
 'busi',
 'business',
 'businessman',
 'bust',
 'butcher',
 'butler',
 'butt',
 'button',
 'buy',
 'buzz',
 'cabin',
 'caesar',
 'cage',
 'cairo',
 'cal',
 'california',
 'calvin',
 'camcord',
 'came',
 'camera',
 'cameraman',
 'camerondiaz',
 'camp',
 'campaign',
 'campbell',
 'campu',
 'canada',
 'canadian',
 'cancer',
 'candi',
 'candid',
 'canin',
 'cannib',
 'canuxploit',
 'capabl',
 'caper',
 'capit',
 'capt',
 'captain',
 'captiv',
 'captur',
 'capture',
 'car',
 'caraccid',
 'carchas',
 'carcrash',
 'card',
 'care',
 'career',
 'carefre',
 'caretak',
 'careymulligan',
 'caribbean',
 'carjourney',
 'carl',
 'carlagugino',
 'carmen',
 'carol',
 'carolina',
 'carrac',
 'carri',
 'carrie',
 'cartel',
 'carter',
 'cartoon',
 'caryelw',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castl',
 'cat',
 'cataclysm',
 'catastroph',
 'catch',
 'cateblanchett',
 'catherinedeneuv',
 'catherinekeen',
 'catherinezeta',
 'cathol',
 'catholic',
 'cattl',
 'caught',
 'caus',
 'cavalri',
 'cave',
 'cavemen',
 'celebr',
 'celebration',
 'cell',
 'cellphon',
 'cemeteri',
 'center',
 'centr',
 'central',
 'centuri',
 'centuries',
 'century',
 'ceo',
 'certain',
 'chad',
 'chain',
 'chainsaw',
 'challeng',
 'chamber',
 'champion',
 'championship',
 'chanc',
 'chance',
 'chang',
 'change',
 'changed',
 'changes',
 'channingtatum',
 'chao',
 'chaos',
 'chaotic',
 'chapter',
 'charact',
 'character',
 'characters',
 'charg',
 'charismat',
 'charl',
 'charli',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charm',
 'chart',
 'chase',
 'chauffeur',
 'chazzpalminteri',
 'cheat',
 'check',
 'cheerlead',
 'chef',
 'chemic',
 'cher',
 'chevychas',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabus',
 'childhero',
 'childhood',
 'childprodigi',
 'children',
 'chill',
 'chimp',
 'china',
 'chines',
 'chip',
 'chipmunk',
 'chiwetelejiofor',
 'chloe',
 'chloëgracemoretz',
 'chloësevigni',
 'chocol',
 'choic',
 'choice',
 'choos',
 'chosen',
 'chowyun',
 'chri',
 'chriscolumbu',
 'chriscoop',
 'chrisevan',
 'chrishemsworth',
 'chrisklein',
 'chrispin',
 'chrisrock',
 'christ',
 'christian',
 'christianbal',
 'christianslat',
 'christin',
 'christinaappleg',
 'christinaricci',
 'christma',
 'christmas',
 'christmasparti',
 'christmastre',
 'christoph',
 'christopherlambert',
 'christopherlloyd',
 'christophernolan',
 'christopherplumm',
 'christopherwalken',
 'christophwaltz',
 'chrisweitz',
 'chronicl',
 'chuck',
 'church',
 'cia',
 'ciaránhind',
 'cigarettesmok',
 'cillianmurphi',
 'cinema',
 'circl',
 'circu',
 'circuit',
 'circumst',
 'citi',
 'citizen',
 'city',
 'civil',
 'civilian',
 'civilwar',
 'claim',
 'clair',
 'clairedan',
 'claireforlani',
 'clan',
 'clark',
 'clash',
 'class',
 'classdiffer',
 'classic',
 'classmat',
 'classroom',
 'claudevandamm',
 'clay',
 'clean',
 'clear',
 'clerk',
 'clever',
 'client',
 'clients',
 'cliff',
 'climat',
 'climb',
 'clinteastwood',
 'cliveowen',
 'clock',
 'clone',
 'close',
 'closer',
 'cloud',
 'clown',
 'club',
 'clue',
 'clueless',
 'clutch',
 'coach',
 'coast',
 'cocain',
 'code',
 'coffin',
 'cohen',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colin',
 'colinfarrel',
 'colinfirth',
 'collaps',
 'colleagu',
 'collect',
 'collector',
 'colleg',
 'college',
 'collid',
 'collis',
 'colombia',
 'colonel',
 'coloni',
 'color',
 'colorado',
 'coma',
 'combat',
 'combin',
 'come',
 'comeback',
 'comed',
 'comedi',
 'comedian',
 'comedy',
 'comet',
 'comfort',
 'comic',
 'coming',
 'comingofag',
 'comingout',
 'command',
 'commando',
 'commerci',
 'commiss',
 'commit',
 'common',
 'commun',
 'communist',
 'community',
 'compani',
 'companion',
 'company',
 'compet',
 'competit',
 'competition',
 'complet',
 'complex',
 'complic',
 'compos',
 'compuls',
 'comput',
 'computerviru',
 'conan',
 'concern',
 'concert',
 'concoct',
 'condit',
 'condition',
 'conduct',
 'confeder',
 'confess',
 'confid',
 'confin',
 'conflict',
 'confront',
 'confus',
 'congress',
 'conman',
 'connect',
 'connecticut',
 'connel',
 'connor',
 'conquer',
 'consequ',
 'consequences',
 'conserv',
 'consid',
 'conspir',
 'conspiraci',
 'conspiracy',
 'constant',
 'constantli',
 'construct',
 'consum',
 'contact',
 'contain',
 'contemporari',
 'contend',
 'content',
 'contest',
 'continu',
 'contract',
 'contractor',
 'control',
 'controversi',
 'convent',
 'converg',
 'convers',
 'convict',
 'convinc',
 'cook',
 ...]

In [48]:
from sklearn.metrics.pairwise import cosine_similarity
similarities =cosine_similarity(vectors)

In [49]:
similarities.shape

(4806, 4806)

In [50]:
# df[df['title']=='Avatar'].index[0]

In [51]:
sorted(list(enumerate(similarities[0])),reverse=True,key=lambda x:x[1])

[(0, 1.0000000000000002),
 (1216, 0.28676966733820225),
 (2409, 0.26901379342448517),
 (3730, 0.2605130246476754),
 (507, 0.255608593705383),
 (539, 0.25038669783359574),
 (582, 0.24511108480187255),
 (1204, 0.24455799402225925),
 (1194, 0.2367785320221084),
 (61, 0.23179316248638276),
 (778, 0.23174488732966073),
 (4048, 0.2278389747471728),
 (1920, 0.2252817784447915),
 (2786, 0.21853668936906193),
 (172, 0.21239769762143662),
 (972, 0.2108663315950723),
 (322, 0.2105263157894737),
 (2333, 0.20443988269091456),
 (3608, 0.20437977982832192),
 (260, 0.20395079136182276),
 (151, 0.2029530274475215),
 (4192, 0.2029530274475215),
 (1444, 0.20277677641345318),
 (74, 0.2024645717996314),
 (1089, 0.2020475485519274),
 (3675, 0.1979082783981174),
 (973, 0.19767387315371682),
 (577, 0.1976738731537168),
 (47, 0.19672236884115843),
 (2971, 0.1925214071641298),
 (942, 0.19134594929397597),
 (495, 0.19088542889273336),
 (1201, 0.19088542889273336),
 (305, 0.19007487139298027),
 (4, 0.1892994097121204),
 (4405, 0.18731716231633883),
 (94, 0.1873171623163388),
 (27, 0.18693292157876878),
 (3327, 0.1860807318911967),
 (1275, 0.18394180184548975),
 (1329, 0.18394180184548975),
 (2999, 0.1813690625275029),
 (3999, 0.18074256993863339),
 (83, 0.17996850826633903),
 (1071, 0.17954621161490197),
 (220, 0.1777046633277277),
 (184, 0.177343107178349),
 (1321, 0.17699808135119718),
 (168, 0.17521916101261562),
 (2204, 0.17521916101261562),
 (4336, 0.17521916101261562),
 (931, 0.1748149640244195),
 (36, 0.17316974359835272),
 (373, 0.17292861596651865),
 (300, 0.1711905958155815),
 (3538, 0.1711905958155815),
 (3162, 0.17040572913692198),
 (1982, 0.16943474841747155),
 (661, 0.1675415633166782),
 (529, 0.16742770563222897),
 (1831, 0.16742770563222897),
 (91, 0.16692446522239718),
 (41, 0.16563698349810535),
 (67, 0.16452254913212452),
 (150, 0.16426202236672155),
 (1537, 0.16222142113076254),
 (342, 0.16122923187750418),
 (595, 0.16059101370939324),
 (31, 0.15907119074394446),
 (2515, 0.15907119074394446),
 (1178, 0.15789473684210528),
 (4010, 0.15737789507292674),
 (2731, 0.15609763526361567),
 (149, 0.15511334686589626),
 (838, 0.1540171257313038),
 (26, 0.15389675281277312),
 (187, 0.15389675281277312),
 (1383, 0.152008377581442),
 (111, 0.15018785229652767),
 (1344, 0.15018785229652767),
 (311, 0.15018785229652765),
 (52, 0.14843120879858804),
 (513, 0.14843120879858804),
 (2075, 0.14808721943977307),
 (7, 0.14673479641335554),
 (2760, 0.14659886790209342),
 (127, 0.14601068654819693),
 (579, 0.14567913668701626),
 (581, 0.14567913668701626),
 (108, 0.14509525002200235),
 (1297, 0.14509525002200235),
 (466, 0.14509525002200233),
 (1396, 0.14421498760030763),
 (1479, 0.1442149876003076),
 (1355, 0.14350946197048198),
 (1938, 0.14350946197048198),
 (275, 0.1433848336691011),
 (294, 0.1433848336691011),
 (3354, 0.1433848336691011),
 (1056, 0.1419745572840903),
 (1273, 0.1419745572840903),
 (490, 0.14159846508095775),
 (1488, 0.14159846508095775),
 (413, 0.1411956236812263),
 (461, 0.1411956236812263),
 (568, 0.1411956236812263),
 (2496, 0.1411956236812263),
 (95, 0.14048787173725413),
 (17, 0.13977653617040256),
 (46, 0.1391037210186643),
 (3409, 0.1391037210186643),
 (1965, 0.13872950617564817),
 (56, 0.13834289277321493),
 (249, 0.13834289277321493),
 (1327, 0.13834289277321493),
 (3781, 0.13834289277321493),
 (72, 0.13710212427677043),
 (843, 0.13710212427677043),
 (859, 0.13710212427677043),
 (2169, 0.13710212427677043),
 (4538, 0.13629325512727639),
 (476, 0.13530201829834768),
 (505, 0.13530201829834768),
 (668, 0.13530201829834768),
 (935, 0.13530201829834768),
 (3982, 0.13530201829834768),
 (1808, 0.13518451760896877),
 (4348, 0.13497638119975428),
 (1322, 0.13476498501489081),
 (158, 0.13369695534647594),
 (502, 0.13369695534647594),
 (777, 0.13369695534647594),
 (126, 0.13334518676566626),
 (1560, 0.13334518676566626),
 (1373, 0.1324532357065044),
 (2378, 0.1324532357065044),
 (2584, 0.1324532357065044),
 (4079, 0.13157894736842107),
 (2133, 0.13124359177794215),
 (1015, 0.12988108336653278),
 (2181, 0.12988108336653278),
 (3622, 0.12988108336653278),
 (134, 0.12977713690461004),
 (368, 0.12977713690461004),
 (1774, 0.12977713690461004),
 (2873, 0.12892051277806202),
 (14, 0.12824729401064427),
 (138, 0.12824729401064427),
 (369, 0.12824729401064427),
 (1086, 0.12824729401064427),
 (2686, 0.12824729401064427),
 (4230, 0.12824729401064427),
 (487, 0.12725695259515557),
 (773, 0.12725695259515557),
 (2970, 0.12725695259515557),
 (937, 0.126673647984535),
 (2480, 0.12565617248750865),
 (1741, 0.12565617248750863),
 (166, 0.12515654358043973),
 (754, 0.12515654358043973),
 (2450, 0.12515654358043973),
 (3628, 0.12515654358043973),
 (483, 0.12487810821089254),
 (1096, 0.12487810821089254),
 (1158, 0.12487810821089254),
 (2652, 0.12487810821089254),
 (102, 0.12462194771917919),
 (84, 0.12361284651454937),
 (208, 0.12262786789699316),
 (3376, 0.12262786789699316),
 (1878, 0.12262786789699313),
 (438, 0.12227899701112963),
 (557, 0.12227899701112963),
 (1299, 0.12227899701112963),
 (2331, 0.12166606584807191),
 (2674, 0.12166606584807191),
 (3083, 0.12166606584807191),
 (139, 0.12072654548783007),
 (68, 0.1204950466257556),
 (781, 0.1204950466257556),
 (1004, 0.1204950466257556),
 (1274, 0.1204950466257556),
 (1658, 0.1204950466257556),
 (1002, 0.11980845957463077),
 (549, 0.11959121830873498),
 (870, 0.11959121830873498),
 (900, 0.11959121830873498),
 (3235, 0.11959121830873498),
 (1047, 0.11846977555181847),
 (1833, 0.11846977555181847),
 (2060, 0.11846977555181847),
 (2741, 0.11846977555181847),
 (4673, 0.11846977555181847),
 (3721, 0.11803342130469506),
 (1673, 0.11803342130469505),
 (1715, 0.11803342130469505),
 (2789, 0.11803342130469505),
 (4000, 0.11803342130469505),
 (160, 0.11712303424679457),
 (182, 0.11707322644771176),
 (278, 0.11707322644771176),
 (454, 0.11707322644771176),
 (1617, 0.11707322644771176),
 (2284, 0.11707322644771176),
 (28, 0.116543309349613),
 (122, 0.116543309349613),
 (422, 0.116543309349613),
 (678, 0.116543309349613),
 (589, 0.1163350101494222),
 (2547, 0.11587244366483038),
 (1497, 0.11551284429847784),
 (3212, 0.11506355109724453),
 (189, 0.1147078669352809),
 (1220, 0.1147078669352809),
 (236, 0.11470786693528087),
 (1301, 0.11470786693528087),
 (85, 0.1141270638770543),
 (432, 0.11357771260606365),
 (1418, 0.11357771260606365),
 (50, 0.11295649894498103),
 (1616, 0.11295649894498103),
 (123, 0.1124803176664619),
 (420, 0.1124803176664619),
 (536, 0.1124803176664619),
 (889, 0.11243619908556624),
 (3147, 0.11239029738980327),
 (256, 0.11164843913471803),
 (808, 0.11164843913471803),
 (1348, 0.11164843913471803),
 (1575, 0.11164843913471803),
 (2372, 0.11141412945539662),
 (3309, 0.11141412945539662),
 (1512, 0.11141412945539661),
 (87, 0.11128297681493143),
 (121, 0.11128297681493143),
 (232, 0.11128297681493143),
 (4468, 0.11128297681493143),
 (206, 0.11092107999698035),
 (238, 0.11092107999698035),
 (228, 0.11037769642208699),
 (81, 0.11020775375559676),
 (1574, 0.11020775375559674),
 (3428, 0.10968169942141637),
 (21, 0.10968169942141635),
 (449, 0.10968169942141635),
 (1031, 0.10968169942141635),
 (1945, 0.10968169942141635),
 (2148, 0.10968169942141635),
 (3008, 0.10968169942141635),
 (692, 0.10936965981495178),
 (200, 0.10882143751650175),
 (627, 0.10882143751650175),
 (653, 0.10882143751650175),
 (1524, 0.10882143751650175),
 (307, 0.10876595882948199),
 (5, 0.10838874619051501),
 (740, 0.10838874619051501),
 (3093, 0.10838874619051501),
 (3630, 0.10838874619051501),
 (786, 0.10814761408717502),
 (3498, 0.10814761408717502),
 (4777, 0.10814761408717502),
 (229, 0.1074861545850028),
 (572, 0.10743376064838502),
 (939, 0.1068366854693644),
 (332, 0.106676149412533),
 (472, 0.106676149412533),
 (1237, 0.106676149412533),
 (170, 0.10650358071057624),
 (262, 0.10650358071057624),
 (1166, 0.10619884881071831),
 (1501, 0.10619884881071831),
 (1745, 0.10619884881071831),
 (2161, 0.10619884881071831),
 (2634, 0.10619884881071831),
 (4135, 0.10619884881071831),
 (467, 0.10559715077387793),
 (541, 0.10559715077387793),
 (1496, 0.10559715077387793),
 (131, 0.10526315789473685),
 (295, 0.10526315789473685),
 (2072, 0.10526315789473685),
 (3340, 0.10526315789473685),
 (2498, 0.10471347707292386),
 (75, 0.10390486669322622),
 (223, 0.10390486669322622),
 (687, 0.10390486669322622),
 (814, 0.10390486669322622),
 (1195, 0.10390486669322622),
 (1771, 0.10390486669322622),
 (2817, 0.10390486669322622),
 (654, 0.10385162309931599),
 (2439, 0.10385162309931599),
 (105, 0.1037571695799112),
 (233, 0.1037571695799112),
 (624, 0.1037571695799112),
 (2323, 0.1037571695799112),
 (2456, 0.1037571695799112),
 (2521, 0.1037571695799112),
 (3055, 0.1037571695799112),
 (3621, 0.1037571695799112),
 (3839, 0.1037571695799112),
 (1455, 0.10301070542879115),
 (10, 0.10259783520851541),
 (1082, 0.10259783520851541),
 (3152, 0.10259783520851541),
 (3634, 0.10259783520851541),
 (3755, 0.10259783520851541),
 (3874, 0.10259783520851541),
 (4097, 0.10259783520851541),
 (2106, 0.10218988991416095),
 (2762, 0.10147651372376076),
 (3663, 0.10147651372376076),
 (3954, 0.10147651372376076),
 (3441, 0.10138838820672659),
 (508, 0.101338918387628),
 (1294, 0.101338918387628),
 (2247, 0.10133891838762799),
 (1405, 0.10060545457319173),
 (1439, 0.10060545457319173),
 (2099, 0.10060545457319173),
 (312, 0.10012523486435178),
 (330, 0.10012523486435178),
 (643, 0.10012523486435178),
 (988, 0.10012523486435178),
 (1037, 0.10012523486435178),
 (1614, 0.10012523486435178),
 (35, 0.09933992677987831),
 (157, 0.09933992677987831),
 (319, 0.09933992677987831),
 (325, 0.09933992677987831),
 (715, 0.09933992677987831),
 (1077, 0.09933992677987831),
 (1280, 0.09933992677987831),
 (1884, 0.09933992677987831),
 (2053, 0.09933992677987831),
 (4018, 0.09933992677987831),
 (4198, 0.09933992677987831),
 (4490, 0.09933992677987831),
 (363, 0.09909250441117726),
 (491, 0.09909250441117726),
 (266, 0.0989541391990587),
 (445, 0.0989541391990587),
 (510, 0.0989541391990587),
 (3620, 0.0989541391990587),
 (3783, 0.0989541391990587),
 (3935, 0.0989541391990587),
 (1775, 0.09836118442057921),
 (410, 0.0978231976089037),
 (480, 0.0978231976089037),
 (535, 0.0978231976089037),
 (898, 0.0978231976089037),
 (1109, 0.0978231976089037),
 (1401, 0.0978231976089037),
 (1823, 0.0978231976089037),
 (2253, 0.0978231976089037),
 (33, 0.09733285267845754),
 (148, 0.09733285267845754),
 (263, 0.09733285267845754),
 (878, 0.09733285267845754),
 (1156, 0.09733285267845754),
 (1727, 0.09733285267845754),
 (1942, 0.09733285267845754),
 (2787, 0.09733285267845754),
 (4256, 0.09733285267845754),
 (4403, 0.09733285267845754),
 (4472, 0.09733285267845754),
 (9, 0.0967301666813349),
 (334, 0.0967301666813349),
 (371, 0.09567297464698798),
 (412, 0.09567297464698798),
 (2241, 0.09567297464698798),
 (2556, 0.09567297464698798),
 (4545, 0.09558988911273408),
 (362, 0.09544271444636668),
 (791, 0.09544271444636668),
 (1573, 0.09544271444636668),
 (2562, 0.09544271444636668),
 (4203, 0.09544271444636668),
 (18, 0.09493290614465533),
 (11, 0.09464970485606021),
 (587, 0.09464970485606021),
 (660, 0.09365858115816941),
 (920, 0.09365858115816941),
 (980, 0.09365858115816941),
 (1276, 0.09365858115816941),
 (1357, 0.09365858115816941),
 (1474, 0.09365858115816941),
 (1686, 0.09365858115816941),
 (1692, 0.09365858115816941),
 (1721, 0.09365858115816941),
 (2396, 0.09365858115816941),
 (2488, 0.09365858115816941),
 (2592, 0.09365858115816941),
 (2645, 0.09365858115816941),
 (2650, 0.09365858115816941),
 (2820, 0.09365858115816941),
 (3537, 0.09365858115816941),
 (3720, 0.09365858115816941),
 (4331, 0.09365858115816941),
 (4502, 0.09365858115816941),
 (301, 0.09365858115816939),
 (129, 0.09269795493186431),
 (243, 0.09269795493186431),
 (279, 0.09269795493186431),
 (473, 0.09269795493186431),
 (596, 0.09269795493186431),
 (813, 0.09269795493186431),
 (1446, 0.09269795493186431),
 (1701, 0.09269795493186431),
 (3407, 0.09269795493186431),
 (785, 0.09243423333081695),
 (219, 0.09197090092274487),
 (244, 0.09197090092274487),
 (511, 0.09197090092274487),
 (1756, 0.09197090092274487),
 (2093, 0.09197090092274487),
 (2651, 0.09197090092274487),
 (3736, 0.09197090092274487),
 (230, 0.09183979479633063),
 (799, 0.09183979479633063),
 (239, 0.09125667909262308),
 (2570, 0.09125667909262308),
 (43, 0.09086217008485092),
 (602, 0.09086217008485092),
 (997, 0.09086217008485092),
 (1233, 0.09086217008485092),
 (1846, 0.09086217008485092),
 (3881, 0.09086217008485092),
 (12, 0.09037128496931669),
 (88, 0.09037128496931669),
 (167, 0.09037128496931669),
 (356, 0.09037128496931669),
 (400, 0.09037128496931669),
 (1306, 0.09037128496931669),
 (1480, 0.09037128496931669),
 (2251, 0.09037128496931669),
 (2957, 0.09037128496931669),
 (331, 0.08998425413316952),
 (2363, 0.08998425413316952),
 (2796, 0.08998425413316952),
 (2856, 0.08998425413316952),
 (3389, 0.08998425413316952),
 (3443, 0.08998425413316952),
 (3462, 0.08998425413316952),
 (4343, 0.08998425413316952),
 (4353, 0.08998425413316952),
 (274, 0.08977310580745099),
 (1906, 0.0891313035643173),
 (2115, 0.08903057122447033),
 (292, 0.08885233166386385),
 (564, 0.08885233166386385),
 (1027, 0.08885233166386385),
 (2660, 0.08885233166386385),
 (2868, 0.08885233166386385),
 (3322, 0.08885233166386385),
 (169, 0.08830215713766959),
 (270, 0.08830215713766959),
 (618, 0.08830215713766959),
 (1783, 0.08830215713766959),
 (2109, 0.08830215713766959),
 (2713, 0.08830215713766959),
 (2740, 0.08830215713766959),
 (3553, 0.08830215713766959),
 (479, 0.08797691788472335),
 (752, 0.08749572785196143),
 (1832, 0.08749572785196143),
 (2448, 0.08746392856766495),
 (23, 0.08740748201220976),
 (141, 0.08740748201220976),
 (389, 0.08740748201220976),
 (745, 0.08740748201220976),
 (794, 0.08740748201220976),
 (960, 0.08740748201220976),
 (1249, 0.08740748201220976),
 (1259, 0.08740748201220976),
 (3448, 0.08740748201220976),
 (3449, 0.08740748201220976),
 (143, 0.08671099695241201),
 (199, 0.08671099695241201),
 (827, 0.08671099695241201),
 (1530, 0.08671099695241201),
 (2880, 0.08671099695241201),
 (3556, 0.08671099695241201),
 (4516, 0.08671099695241201),
 (4587, 0.08671099695241201),
 (2, 0.08603090020146065),
 (457, 0.08603090020146065),
 (775, 0.08603090020146065),
 (1378, 0.08603090020146065),
 (2583, 0.08603090020146065),
 (3135, 0.08603090020146065),
 (4754, 0.08603090020146065),
 (234, 0.08594700851870801),
 (1019, 0.08594700851870801),
 (2354, 0.08594700851870801),
 (32, 0.08520286456846099),
 (217, 0.08520286456846099),
 (142, 0.08471737420873576),
 (894, 0.08471737420873576),
 (1097, 0.08471737420873576),
 (1142, 0.08471737420873576),
 (1589, 0.08471737420873576),
 (2304, 0.08471737420873576),
 (4560, 0.08471737420873576),
 (48, 0.08447772061910234),
 (190, 0.08447772061910234),
 (1305, 0.08447772061910234),
 (1639, 0.08447772061910234),
 (2968, 0.08447772061910234),
 (62, 0.0837707816583391),
 (381, 0.0837707816583391),
 (534, 0.0837707816583391),
 (1698, 0.0837707816583391),
 (3180, 0.0837707816583391),
 (3218, 0.0837707816583391),
 (3978, 0.0837707816583391),
 (4737, 0.0837707816583391),
 (1, 0.08346223261119858),
 (152, 0.08346223261119858),
 (203, 0.08346223261119858),
 (315, 0.08346223261119858),
 (547, 0.08346223261119858),
 (1688, 0.08346223261119858),
 (2128, 0.08346223261119858),
 (2386, 0.08321783316232578),
 (19, 0.0830812984794528),
 (403, 0.0830812984794528),
 (3905, 0.0830812984794528),
 (45, 0.08240856434303293),
 (2203, 0.08240856434303293),
 (39, 0.08226127456606226),
 (227, 0.08226127456606226),
 (341, 0.08226127456606226),
 (626, 0.08226127456606226),
 (787, 0.08226127456606226),
 (1207, 0.08226127456606226),
 (1749, 0.08226127456606226),
 (2167, 0.08226127456606226),
 (2661, 0.08226127456606226),
 (3140, 0.08226127456606226),
 (3301, 0.08226127456606226),
 (3470, 0.08226127456606226),
 (63, 0.08175191193132876),
 (501, 0.08175191193132876),
 (38, 0.08111071056538127),
 (242, 0.08111071056538127),
 (245, 0.08111071056538127),
 (306, 0.08111071056538127),
 (584, 0.08111071056538127),
 (812, 0.08111071056538127),
 (866, 0.08111071056538127),
 (901, 0.08111071056538127),
 (1269, 0.08111071056538127),
 (1519, 0.08111071056538127),
 (1664, 0.08111071056538127),
 (2339, 0.08111071056538127),
 (2644, 0.08111071056538127),
 (2671, 0.08111071056538127),
 (2865, 0.08111071056538127),
 (2877, 0.08111071056538127),
 (3527, 0.08111071056538127),
 (3926, 0.08111071056538127),
 (4492, 0.08111071056538127),
 (4568, 0.08111071056538127),
 (4626, 0.08111071056538127),
 (4641, 0.08111071056538127),
 (4654, 0.08111071056538127),
 (4657, 0.08111071056538127),
 (51, 0.08048436365855338),
 (164, 0.08000711205939975),
 (854, 0.08000711205939975),
 (899, 0.08000711205939975),
 (1325, 0.08000711205939975),
 (1747, 0.08000711205939975),
 (2683, 0.08000711205939975),
 (3764, 0.08000711205939975),
 (3816, 0.08000711205939975),
 (3851, 0.08000711205939975),
 (486, 0.07992075789278004),
 (103, 0.07987230638308718),
 (222, 0.07987230638308718),
 (1534, 0.07987230638308718),
 (2792, 0.07987230638308718),
 (4506, 0.07987230638308718),
 (1898, 0.0792740035289418),
 (16, 0.07894736842105264),
 (37, 0.07894736842105264),
 (241, 0.07894736842105264),
 (329, 0.07894736842105264),
 (1080, 0.07894736842105264),
 (1161, 0.07894736842105264),
 (2295, 0.07894736842105264),
 (3233, 0.07894736842105264),
 (4316, 0.07894736842105264),
 (193, 0.07878168645790681),
 (153, 0.07868894753646337),
 (776, 0.07868894753646337),
 (1045, 0.07868894753646337),
 (1828, 0.07868894753646337),
 (1926, 0.07868894753646337),
 (3728, 0.07868894753646337),
 (3832, 0.07868894753646337),
 (4279, 0.07868894753646337),
 (4473, 0.07868894753646337),
 (125, 0.07843304784240032),
 (286, 0.0781166566864507),
 (1659, 0.0781166566864507),
 (174, 0.07792865001991967),
 (402, 0.07792865001991967),
 (922, 0.07792865001991967),
 (1113, 0.07792865001991967),
 (2938, 0.07792865001991967),
 (3028, 0.07792865001991967),
 (3091, 0.07792865001991967),
 (3102, 0.07792865001991967),
 (3164, 0.07792865001991967),
 (4341, 0.07792865001991967),
 (1924, 0.07755667343294813),
 (3560, 0.07755667343294813),
 (1282, 0.0770085628656519),
 (40, 0.07694837640638656),
 (96, 0.07694837640638656),
 (101, 0.07694837640638656),
 (112, 0.07694837640638656),
 (207, 0.07694837640638656),
 (632, 0.07694837640638656),
 (737, 0.07694837640638656),
 (1289, 0.07694837640638656),
 (2219, 0.07694837640638656),
 (4268, 0.07694837640638656),
 (4624, 0.07694837640638656),
 (850, 0.07647191129018727),
 (1005, 0.07647191129018727),
 (1139, 0.07647191129018727),
 (1254, 0.07647191129018727),
 (1621, 0.07647191129018727),
 (2165, 0.07647191129018727),
 (2274, 0.07647191129018727),
 (2712, 0.07647191129018727),
 (3430, 0.07647191129018727),
 (4165, 0.07647191129018727),
 (70, 0.076004188790721),
 (82, 0.076004188790721),
 (235, 0.076004188790721),
 (349, 0.076004188790721),
 (492, 0.076004188790721),
 (1290, 0.076004188790721),
 (1523, 0.076004188790721),
 (2449, 0.076004188790721),
 (2916, 0.076004188790721),
 (4558, 0.076004188790721),
 (246, 0.07594632491572426),
 (2005, 0.07543142864047142),
 (3331, 0.07530940414109724),
 (98, 0.07509392614826384),
 (210, 0.07509392614826384),
 (361, 0.07509392614826384),
 (365, 0.07509392614826384),
 (503, 0.07509392614826384),
 (540, 0.07509392614826384),
 (680, 0.07509392614826384),
 (1009, 0.07509392614826384),
 (1293, 0.07509392614826384),
 (2163, 0.07509392614826384),
 (4045, 0.07509392614826384),
 (4205, 0.07509392614826384),
 (2256, 0.07492686492653551),
 (205, 0.07443229275647868),
 (800, 0.07443229275647868),
 (995, 0.07443229275647868),
 (1323, 0.07443229275647868),
 (1521, 0.07443229275647868),
 (1770, 0.07443229275647868),
 (2326, 0.07443229275647868),
 (2551, 0.07443229275647868),
 (2801, 0.07443229275647868),
 (3069, 0.07443229275647868),
 (3117, 0.07443229275647868),
 (3126, 0.07443229275647868),
 (4011, 0.07443229275647868),
 (4412, 0.07443229275647868),
 (4542, 0.07443229275647868),

In [52]:
def recomdations(movie):
    ind = df[df['title']==movie].index[0]
    distances=similarities[ind]
    
    movies = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    
    movies_ind_list=[]
    for i in movies:
        movies_ind_list.append(i[0])
        
    for i in movies_ind_list:
        print(df.iloc[i]['title'])

In [53]:
recomdations('Avatar')

Aliens vs Predator: Requiem
Aliens
Falcon Rising
Independence Day
Titan A.E.

In [54]:
import pickle
pickle.dump(df,open("movies.pkl","wb"))

In [55]:
pickle.dump(similarities,open("similarities.pkl","wb"))